---
name: setup
description: Setup Node.js and pnpm
runs:
  using: composite
  steps:
    - name: 📦 Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.15.4
        package_json_file: package.json
        run_install: false

    - name: 🌎 Setup Node.js
      uses: actions/setup-node@v4
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        node-version-file: package.json
        registry-url: https://registry.npmjs.org
        scope: "@maiar-ai"
        cache: pnpm

    - name: 📦 Install Dependencies
      run: pnpm install --frozen-lockfile --strict-peer-dependencies
      shell: bash
