name: 🎉 Thank Contributor
on:
  pull_request_target:
    types: [closed]

jobs:
  pay-contributor:
    name: 🎉 Thank Contributor
    # Only run this job when the PR is merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: 🎉 Thank Contributor
        run: node .github/scripts/thank-you/thank-contributor.js
        env:
          # Standard Environment Variables
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          # Step Inputs
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
